LICENSE.md
Procfile

closes #10 
Got rid of heroku Procfile

Housekeeping

---

index.js

Trim blanks at both ends of title.

---

.all-contributorsrc
README.md
package-lock.json
package.json

12 contrib list

---

index.js

Pull request created for Results sanitization #17

Updated code for Results sanitization #17

---

index.js

The proposed data structure mentioned in #7 make faster item access,
using the fast property access behavior
of several javascript engines.
In addition, this will also fix issue #4 since any article with the same
url will be updated instead of creating
a new article item.

Changing the data structure to make it faster

---

.dccache
.gitignore
data/accounts.json
data/sources.json
index.js

Prettier format my code on save, that's why it add semicolons and so one

feat: move sources and twitter accounts into a data folder

---

.github/workflows/codeql-analysis.yml

I noticed that the codeql analysis didn't run on push and pull request. 
The reason was that I set the branch to main instead of master 😅

fix: update codeql branch to analyze

---

controller/api/newsAPIController.js

Hello @MizouziE! Here is a PR that targets issue #18
- Adds new function that performs an extra regex evaluation on titles.
If you got any questions let me know!

Adds new function to get accurate title

---

controller/api/newsAPIController.js

Hello team! Here is a PR that targets issue #18.
The solution proposal I develop was lacking some adjustments, as mentioned before by @MizouziE in #18. 
- Adds adjustment to the Regex Function in getTitle()
- Adds .split in line 13 to get the right value
Let me know if you got any questions, I'm eager to continue working with you!

Updated getTitle()

---

app.js
package-lock.json
package.json

Hi @MizouziE here is a PR to solve the issues #34 and #43 
The solution for #34 as suggest by @TAKANOME-DEV was to use the `express-rate-limit` package, so I made those changes, which are:
- I added a maximum of ten requests per minute to all requests, you can see this on `app.js` (_this could be applied individually, but for now my aim is to use it in all requests temporarily and first check what you guys think_)
- In addition I deleted the `path` package.
Let me know if you got any questions, If there's something missing or any suggestions regarding the PR. I'd appreciate it, thanks you guys! 🚀

added request limiter for all requests

---

src/server.js

I changed the 'not found.html' file's path on server.js

not found page path issue fixed

---

.prettierrc.json
package-lock.json
package.json

Hello! 
Here's what was made:
- Added Prettier as a dependency
- Basic config file was setup with the config provided by @TAKANOME-DEV 
I'd really like to receive a review/feedback I'm really new to this.
Thanks in advance!

Added prettier dependency

---

src/controller/mainController.js

path to root fixed

---

src/data/accounts.json

add new twitter handle to politician list

---

src/views/index.html

This is my first contribution to an open source project! The article  linked in the issue #73 post talked about adding additional meta tags with the dimensions of the image for faster rendering on sites like facebook. This could be a possible optimization.

Fix issue 73. Add the meta tag.

---

src/views/index.html

relate #80
closed issue #73
merged PR #76
thnx for useful article

update  meta tag-add width and height

---

src/views/index.html

My first time doing a PR, please let me know if there are any issues.

Added additional og meta tags

---

src/data/accounts.json

I have added twitter handle of minister of power.
Please let me know if I need to do any corrections!. As, I am very beginner to open Source.
Thanks😊

added twitter_handle

---

src/data/sources.json

I added DevBytes link to the src/data/source.jason file. A link to news including sports, tech, etc.

Added a new link

---

src/views/index.html

This is in reference to #40, I got a token from rapid api and created this Next.js website. I will be happy to share the repo also. I am new here and looking for ways to contribute. Thanks everyone.

Added link to sample website on index.html

---

src/data/sources.json

Added The New York Times to news sources as my first contribution to the project.

Added The New York Times to news sources

---

src/data/sources.json

- Fixed this issue https://github.com/MizouziE/energy-prices-api/issues/104#issue-1335898936
- Fixed this issue https://github.com/MizouziE/energy-prices-api/issues/103#issue-1335867592

:link: Changed the better URL

---

src/data/keywords.js

'src/data/keywords.js' file has been updated

Added more to keywords list

---

.all-contributorsrc
README.md
package.json

https://github.com/MizouziE/energy-prices-api/issues/23#issue-1243953402

🔨 Updated Contributors List

---

src/data/sources.json

Fixing issue 107 and 108 by updating the abc news and The times site URL.

fix :107 and 108 issues by updating the abc news and the times site url

---

src/controller/api/newsAPIController.js

- Fixes #97 
- Added regex check for image URL in `src/controller/api/newsAPIController.js`

Fixed broken image for articles from "The Times"

---

src/data/keywords.js

added the commas that I missed in the code review, sorry @rohan9454!

Fixed what @MizouziE missed in code review

---

src/data/sources.json

Added economic times to sources.json

---

src/controller/api/newsAPIController.js
src/routes/api/news.js
src/utils/getSourceImageFromCheerio.js

A new endpoint added that lists:
1. The names of available sources
2. Links to the single source endpoint for each
3. An image for the source

implemented endpoint with list of sources feature

---

package-lock.json
src/controller/api/newsAPIController.js
src/data/regions.json
src/data/sources.json
src/middlewares/existingRegionMiddleware.js
src/routes/api/news.js

api/new/regions showin which regions are currently available    and api/new/region/:regionId for showing sources from a particular region.
Also added regions.json consisting of regions currently available

Implemeted api/new/regions  and api/new/region/:regionId and added region.json

---

src/controller/api/newsAPIController.js
src/utils/paginate.js

Pagination was added to all routes. By default there is no pagination.
page & limit(number of item per page) are the two query parameters.

Added pagination to all routes

---

API_DOCS.md
README.md

Written documentation for developing with the endpoints on a local basis.
In the near future I will have to add similar docs to the RapidAPI instance.
Closes #143

143 adding documentation for the pagination feature

---

src/data/sources.json

For issue #49, added two more news sources to `sources.json`.

Added Euronews, and The Globe and Mail

---

__tests__/integration-tests/routes/news.test.js

Closes #150 
Very basic test, will improve in future

add suite for news sources list endpoint

---

API_DOCS.md
__mocks__/articles.js
__tests__/unit-tests/truncate.test.js
src/controller/api/newsAPIController.js
src/server.js
src/utils/truncate.js

163 feat truncation

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/chore.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/other.yml
.github/PULL_REQUEST_TEMPLATE.md

Add pull request template and update issue templates.
Fixes #130

feat: add pull request template

---

.npmrc

This PR restricts the node version to the version present in the package.json . If user doesnt have that version it will not allow user to build the application

fix:restricted node version to the version metioned in the package.json

---

src/data/sources.json

Made changes to the 'base' in scr/data/source.json so as to make the returned URL work

PR linked with issue #160

---

API_DOCS.md
src/controller/api/newsAPIController.js
src/middlewares/existingSourceMiddleware.js
src/routes/api/news.js

- [ :white_check_mark:] 💡 Feature

feature: update single source endpoint

---

__tests__/unit-tests/existingRegionMiddleware.test.js
package.json
src/middlewares/existingRegionMiddleware.js

Fixes[ #157](https://github.com/Energy-Price-News-API/energy-prices-api/issues/157)
N/A

feat: add existing region middleware tests

---

__mocks__/falsyValues.js
__tests__/unit-tests/existingRegionMiddleware.test.js
__tests__/unit-tests/existingSouceMiddleware.test.js

feat: add existing source middleware tests

---

__tests__/integration-tests/routes/news.test.js

This PR added tests for `/api/news/regions`.
Fixes #151

test: add test for api/news/regions

---

__tests__/integration-tests/routes/news.test.js

Added tests for `/api/news/regions/:regionId`
Fixes #152

test: add tests for /api/news/regions/:regionId

---

__tests__/integration-tests/routes/news.test.js

Added a test suit for API News 
#149

Updated new test.js

---

.all-contributorsrc
__tests__/integration-tests/routes/news.test.js

#153 
Added a test for /api/news/sources/:sourceId

Addition of sources/:sourceId test

---

public/css/not-found.css
src/views/not-found.html

Added redirect to homepage button from 404 page.
Fixes #185 
**On hover**

feat: add redirect to homepage button from 404 page

---

src/controller/api/newsAPIController.js

Signed-off-by: chankruze <chankruze@gmail.com>
This PR fixes the bug: source list endpoint giving incorrect URLs.
Fixes #183

fix #183: source list endpoint giving incorrect URLs

---

.github/workflows/first-interaction.yml

This PR adds the feature "welcome for first time contributors"
Closes #181 
None yet

add welcome action yml

---

.github/workflows/node-ci.yml

Adds a workflow to run all the available test suites.
Closes #182

add test workflow

---

src/views/index.html

chore: add twitter meta tags
This PR adds twitter metadata 
#197

feat: Add twitter metadata 

---

src/views/index.html

Signed-off-by: Aabhas Sao <aabhassao0@gmail.com>
This PR updates the og:image and og:url meta tags with new updated urls.

chore: chore: Change og:image & og:url meta tags

---

__mocks__/mockarticles.js
__tests__/unit-tests/paginate.test.js

Added Test for pagination functionality

Added Pagination Tests

---

src/data/sources.json

Liked to Issue #49 
- Adding new news source: The Economist.
- Prettier formatting: added spaces to the region key value pair

added The Economist to sources

---

src/data/sources.json

This PR add NBC news to source.json
Fixes #49

Add NBC news to source.json

---

src/data/sources.json

This PR adds a new energy articles source (Fox News).

New energy articles source (Fox news)

---

src/data/sources.json

added aaj tak and IEX sources

---

src/data/sources.json

Added Energy Voice and Forbes to data/sources.json
Fixes #49

Added Energy Voice and Forbes 

---

API_DOCS.md

Fix minor typos and grammar mistakes in the API documentation.

docs: correct spelling and grammar in API_DOCS.md
